touch library/arithmetic/matrix/ntm_matrix_arithmetic.adb
touch library/arithmetic/scalar/ntm_scalar_arithmetic.adb
touch library/arithmetic/tensor/ntm_tensor_arithmetic.adb
touch library/arithmetic/vector/ntm_vector_arithmetic.adb
touch library/controller/FNN/convolutional/ntm_controller.adb
touch library/controller/FNN/standard/ntm_controller.adb
touch library/controller/LSTM/convolutional/ntm_activation_gate_vector.adb
touch library/controller/LSTM/convolutional/ntm_controller.adb
touch library/controller/LSTM/convolutional/ntm_forget_gate_vector.adb
touch library/controller/LSTM/convolutional/ntm_hidden_gate_vector.adb
touch library/controller/LSTM/convolutional/ntm_input_gate_vector.adb
touch library/controller/LSTM/convolutional/ntm_output_gate_vector.adb
touch library/controller/LSTM/convolutional/ntm_state_gate_vector.adb
touch library/controller/LSTM/standard/ntm_activation_gate_vector.adb
touch library/controller/LSTM/standard/ntm_controller.adb
touch library/controller/LSTM/standard/ntm_forget_gate_vector.adb
touch library/controller/LSTM/standard/ntm_hidden_gate_vector.adb
touch library/controller/LSTM/standard/ntm_input_gate_vector.adb
touch library/controller/LSTM/standard/ntm_output_gate_vector.adb
touch library/controller/LSTM/standard/ntm_state_gate_vector.adb
touch library/dnc/memory/dnc_addressing.adb
touch library/dnc/memory/dnc_allocation_weighting.adb
touch library/dnc/memory/dnc_backward_weighting.adb
touch library/dnc/memory/dnc_forward_weighting.adb
touch library/dnc/memory/dnc_matrix_content_based_addressing.adb
touch library/dnc/memory/dnc_memory_matrix.adb
touch library/dnc/memory/dnc_memory_retention_vector.adb
touch library/dnc/memory/dnc_precedence_weighting.adb
touch library/dnc/memory/dnc_read_content_weighting.adb
touch library/dnc/memory/dnc_read_vectors.adb
touch library/dnc/memory/dnc_read_weighting.adb
touch library/dnc/memory/dnc_sort_vector.adb
touch library/dnc/memory/dnc_temporal_link_matrix.adb
touch library/dnc/memory/dnc_usage_vector.adb
touch library/dnc/memory/dnc_vector_content_based_addressing.adb
touch library/dnc/memory/dnc_write_content_weighting.adb
touch library/dnc/memory/dnc_write_weighting.adb
touch library/dnc/top/dnc_interface_matrix.adb
touch library/dnc/top/dnc_interface_top.adb
touch library/dnc/top/dnc_interface_vector.adb
touch library/dnc/top/dnc_output_vector.adb
touch library/dnc/top/dnc_top.adb
touch library/dnc/trained/dnc_trained_top.adb
touch library/math/algebra/matrix/ntm_matrix_algebra.adb
touch library/math/algebra/scalar/ntm_scalar_algebra.adb
touch library/math/algebra/tensor/ntm_tensor_algebra.adb
touch library/math/algebra/vector/ntm_vector_algebra.adb
touch library/math/calculus/matrix/ntm_matrix_calculus.adb
touch library/math/calculus/tensor/ntm_tensor_calculus.adb
touch library/math/calculus/vector/ntm_vector_calculus.adb
touch library/math/function/matrix/ntm_matrix_function.adb
touch library/math/function/scalar/ntm_scalar_function.adb
touch library/math/function/vector/ntm_vector_function.adb
touch library/math/statitics/matrix/ntm_matrix_statitics.adb
touch library/math/statitics/scalar/ntm_scalar_statitics.adb
touch library/math/statitics/vector/ntm_vector_statitics.adb
touch library/ntm/memory/ntm_addressing.adb
touch library/ntm/memory/ntm_matrix_content_based_addressing.adb
touch library/ntm/memory/ntm_vector_content_based_addressing.adb
touch library/ntm/read_heads/ntm_reading.adb
touch library/ntm/top/ntm_interface_matrix.adb
touch library/ntm/top/ntm_interface_top.adb
touch library/ntm/top/ntm_interface_vector.adb
touch library/ntm/top/ntm_output_vector.adb
touch library/ntm/top/ntm_top.adb
touch library/ntm/trained/ntm_trained_top.adb
touch library/ntm/write_heads/ntm_erasing.adb
touch library/ntm/write_heads/ntm_writing.adb
touch library/state/feedback/ntm_state_feedback.adb
touch library/state/outputs/ntm_state_outputs.adb
touch library/state/top/ntm_state_top.adb
touch library/trainer/differentiation/ntm_matrix_controller_differentiation.adb
touch library/trainer/differentiation/ntm_vector_controller_differentiation.adb
touch library/trainer/FNN/ntm_fnn_b_trainer.adb
touch library/trainer/FNN/ntm_fnn_d_trainer.adb
touch library/trainer/FNN/ntm_fnn_k_trainer.adb
touch library/trainer/FNN/ntm_fnn_trainer.adb
touch library/trainer/FNN/ntm_fnn_u_trainer.adb
touch library/trainer/FNN/ntm_fnn_v_trainer.adb
touch library/trainer/FNN/ntm_fnn_w_trainer.adb
touch library/trainer/LSTM/activation/ntm_lstm_activation_b_trainer.adb
touch library/trainer/LSTM/activation/ntm_lstm_activation_d_trainer.adb
touch library/trainer/LSTM/activation/ntm_lstm_activation_k_trainer.adb
touch library/trainer/LSTM/activation/ntm_lstm_activation_trainer.adb
touch library/trainer/LSTM/activation/ntm_lstm_activation_u_trainer.adb
touch library/trainer/LSTM/activation/ntm_lstm_activation_v_trainer.adb
touch library/trainer/LSTM/activation/ntm_lstm_activation_w_trainer.adb
touch library/trainer/LSTM/forget/ntm_lstm_forget_b_trainer.adb
touch library/trainer/LSTM/forget/ntm_lstm_forget_d_trainer.adb
touch library/trainer/LSTM/forget/ntm_lstm_forget_k_trainer.adb
touch library/trainer/LSTM/forget/ntm_lstm_forget_trainer.adb
touch library/trainer/LSTM/forget/ntm_lstm_forget_u_trainer.adb
touch library/trainer/LSTM/forget/ntm_lstm_forget_v_trainer.adb
touch library/trainer/LSTM/forget/ntm_lstm_forget_w_trainer.adb
touch library/trainer/LSTM/input/ntm_lstm_input_b_trainer.adb
touch library/trainer/LSTM/input/ntm_lstm_input_d_trainer.adb
touch library/trainer/LSTM/input/ntm_lstm_input_k_trainer.adb
touch library/trainer/LSTM/input/ntm_lstm_input_trainer.adb
touch library/trainer/LSTM/input/ntm_lstm_input_u_trainer.adb
touch library/trainer/LSTM/input/ntm_lstm_input_v_trainer.adb
touch library/trainer/LSTM/input/ntm_lstm_input_w_trainer.adb
touch library/trainer/LSTM/output/ntm_lstm_output_b_trainer.adb
touch library/trainer/LSTM/output/ntm_lstm_output_d_trainer.adb
touch library/trainer/LSTM/output/ntm_lstm_output_k_trainer.adb
touch library/trainer/LSTM/output/ntm_lstm_output_trainer.adb
touch library/trainer/LSTM/output/ntm_lstm_output_u_trainer.adb
touch library/trainer/LSTM/output/ntm_lstm_output_v_trainer.adb
touch library/trainer/LSTM/output/ntm_lstm_output_w_trainer.adb
touch library/transformer/components/ntm_masked_multi_head_attention.adb
touch library/transformer/components/ntm_masked_scaled_dot_product_attention.adb
touch library/transformer/components/ntm_multi_head_attention.adb
touch library/transformer/components/ntm_scaled_dot_product_attention.adb
touch library/transformer/controller/fnn/ntm_fnn.adb
touch library/transformer/controller/lstm/ntm_lstm.adb
touch library/transformer/functions/ntm_layer_norm.adb
touch library/transformer/functions/ntm_positional_encoding.adb
touch library/transformer/inputs/ntm_inputs_vector.adb
touch library/transformer/inputs/ntm_keys_vector.adb
touch library/transformer/inputs/ntm_queries_vector.adb
touch library/transformer/inputs/ntm_values_vector.adb
touch library/transformer/top/ntm_controller.adb
touch library/transformer/top/ntm_decoder.adb
touch library/transformer/top/ntm_encoder.adb
